### ISSUE TITLE
Setting custom attribute to blank gives 500 error

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/scim#2]
The following code throws NPE (500 error):

```
//Assume oxEnrollmentCode was previously populated
Response response=client.getUserById(user_inum, null, null);
UserResource u = response.readEntity(UserResource.class);
CustomAttributes attrs = u.getCustomAttributes(USER_EXT_SCHEMA_ID);	
logger.debug(attrs.getValue("oxEnrollmentCode", String.class));
		
attrs.setAttribute("oxEnrollmentCode", "");
response=client.updateUser(u, u.getId(), null, null);
		
logger.debug(response.readEntity(String.class));
```

**oxtrust.log**:
```
2020-06-12 13:19:01,659 ERROR [qtp1590550415-12] [gluu.oxtrust.ws.rs.scim2.UserWebService] (UserWebService.java:180) - Failure at updateUser method
java.lang.NullPointerException: null
	at org.gluu.persist.impl.BaseEntryManager.collectAttributeModifications(BaseEntryManager.java:382) ~[oxcore-persistence-core-4.1.0.Final.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.merge(BaseEntryManager.java:229) ~[oxcore-persistence-core-4.1.0.Final.jar:?]
	at org.gluu.persist.couchbase.impl.CouchbaseEntryManager.merge(CouchbaseEntryManager.java:121) ~[oxcore-persistence-couchbase-4.1.0.Final.jar:?]
	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.gluu.persist.EntityManager$PersistenceEntryManager$479440844$Proxy$_$$_WeldClientProxy.merge(Unknown Source) ~[weld-core-impl-3.1.2.Final.jar:?]
	at org.gluu.oxtrust.service.scim2.UserPersistenceHelper.updatePerson(UserPersistenceHelper.java:74) ~[classes/:?]
	at org.gluu.oxtrust.service.scim2.Scim2UserService.replacePersonInfo(Scim2UserService.java:534) ~[classes/:?]
	at org.gluu.oxtrust.service.scim2.Scim2UserService.updateUser(Scim2UserService.java:509) ~[classes/:?]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService.updateUser(UserWebService.java:171) ~[classes/:?]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldSubclass.updateUser(Unknown Source) ~[classes/:?]
	at org.gluu.oxtrust.service.scim2.interceptor.UserWebServiceDecorator.updateUser(UserWebServiceDecorator.java:127) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.jboss.weld.annotated.runtime.InvokableAnnotatedMethod.invokeOnInstance(InvokableAnnotatedMethod.java:86) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:78) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.DecoratorProxyMethodHandler.doInvoke(DecoratorProxyMethodHandler.java:67) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.interceptor.util.proxy.TargetInstanceProxyMethodHandler.invoke(TargetInstanceProxyMethodHandler.java:33) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.TargetBeanInstance.invoke(TargetBeanInstance.java:91) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_Weld$Proxy$.updateUser(Unknown Source) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.gluu.oxtrust.service.scim2.interceptor.ReferenceURIInterceptor.manage(ReferenceURIInterceptor.java:70) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:81) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldSubclass.updateUser(Unknown Source) ~[classes/:?]
	at org.gluu.oxtrust.ws.rs.scim2.UserWebService$Proxy$_$$_WeldClientProxy.updateUser(Unknown Source) ~[classes/:?]
```

**Comment by jgomer2001** [comment]
Commit 58f88f5 is not part of this issue
